FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/training /app
COPY data /app/data
CMD ["python", "train.py", "--data-path", "data/credit_train.parquet"]
